version: '3'
services:
  mysql:
    image: "mysql:5.6"
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw-Oo
      MYSQL_DATABASE: phpipam
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/
  phpipam:
    image: "pierrecdn/phpipam"
    container_name: "phpipam"
    environment:
      MYSQL_ENV_MYSQL_ROOT_PASSWORD: my-secret-pw-Oo
      MYSQL_ENV_MYSQL_USER: root
      MYSQL_ENV_MYSQL_HOST: mysql
      MYSQL_ENV_MYSQL_DB: phpipam
    links:
      - mysql
    depends_on:
      - mysql
  nginx:
    image: "nginx:alpine"
    container_name: "nginx"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 4433:4433
      - 8080:8080
    links:
      - phpipam
  